/**
 * Curated resume/ATS keyword allowlist used for deterministic JD matching.
 * Terms are matched with word-boundary-aware regex (see jd-keyword-extract.ts).
 * Multi-word phrases should appear here explicitly so they match before single tokens.
 */

const LANGUAGES = [
  "c++",
  "c#",
  "f#",
  "objective-c",
  "python",
  "javascript",
  "typescript",
  "java",
  "kotlin",
  "scala",
  "go",
  "golang",
  "rust",
  "swift",
  "ruby",
  "php",
  "perl",
  "r",
  "matlab",
  "sql",
  "bash",
  "shell",
  "lua",
  "dart",
  "elixir",
  "erlang",
  "clojure",
  "haskell",
  "julia",
  "nim",
  "zig",
  "solidity",
  "vba",
  "apex",
  "groovy",
  "cobol",
  "fortran",
  "vhdl",
  "systemverilog",
];

const WEB_PLATFORM = [
  "react",
  "react native",
  "react.js",
  "next.js",
  "nextjs",
  "angular",
  "vue",
  "vue.js",
  "svelte",
  "nuxt",
  "ember",
  "ember.js",
  "jquery",
  "webpack",
  "vite",
  "rollup",
  "parcel",
  "esbuild",
  "babel",
  "eslint",
  "prettier",
  "rxjs",
  "tailwind",
  "tailwind css",
  "tailwindcss",
  "bootstrap",
  "material-ui",
  "mui",
  "chakra ui",
  "antd",
  "redux",
  "mobx",
  "zustand",
  "recoil",
  "apollo client",
  "relay",
  "htmx",
  "hotwire",
  "turbo",
  "storybook",
  "playwright",
  "cypress",
  "jest",
  "vitest",
  "mocha",
  "karma",
  "jasmine",
  "enzyme",
  "testing library",
];

const BACKEND_APIS = [
  "node.js",
  "nodejs",
  "express",
  "nestjs",
  "fastify",
  "koa",
  "django",
  "flask",
  "fastapi",
  "cherrypy",
  "tornado",
  "celery",
  "rails",
  "ruby on rails",
  "sinatra",
  "spring",
  "spring boot",
  "springboot",
  "micronaut",
  "quarkus",
  "ktor",
  "akka",
  "laravel",
  "symfony",
  "aspnet",
  "asp.net",
  ".net",
  "dotnet",
  "dotnet core",
  ".net core",
  "entity framework",
  "grpc",
  "graphql",
  "apollo server",
  "openapi",
  "swagger",
  "protobuf",
  "protocol buffers",
  "avro",
  "thrift",
  "soap",
  "rest",
  "restful",
  "oauth",
  "oauth2",
  "oidc",
  "openid connect",
  "saml",
  "jwt",
  "websockets",
  "websocket",
  "socket.io",
  "signalr",
  "zeromq",
  "mqtt",
  "rabbitmq",
  "activemq",
  "nats",
  "memcached",
];

const DATA_ML = [
  "tensorflow",
  "pytorch",
  "torch",
  "jax",
  "keras",
  "mxnet",
  "onnx",
  "cuda",
  "cudnn",
  "tensorrt",
  "scikit-learn",
  "sklearn",
  "pandas",
  "numpy",
  "scipy",
  "matplotlib",
  "seaborn",
  "opencv",
  "pillow",
  "xgboost",
  "lightgbm",
  "catboost",
  "spark ml",
  "mlflow",
  "wandb",
  "weights & biases",
  "kubeflow",
  "ray",
  "ml",
  "machine learning",
  "deep learning",
  "neural networks",
  "neural network",
  "cnn",
  "rnn",
  "lstm",
  "transformers",
  "stable diffusion",
  "diffusion models",
  "gan",
  "autoencoder",
  "reinforcement learning",
  "nlp",
  "natural language processing",
  "computer vision",
  "object detection",
  "instance segmentation",
  "semantic segmentation",
  "pose estimation",
  "slam",
  "sensor fusion",
  "semantic fusion",
  "kalman filter",
  "particle filter",
  "localization",
  "mapping",
  "occupancy grid",
  "occupancy networks",
  "llm",
  "llms",
  "large language models",
  "rag",
  "retrieval augmented generation",
  "vector database",
  "embedding",
  "embeddings",
  "fine-tuning",
  "lora",
  "peft",
  "rlhf",
  "human feedback",
  "speech recognition",
  "tts",
  "text to speech",
  "asr",
];

const DATA_ENG = [
  "apache spark",
  "spark",
  "apache flink",
  "flink",
  "apache beam",
  "beam",
  "apache kafka",
  "kafka",
  "kafka streams",
  "ksql",
  "rabbit streams",
  "apache airflow",
  "airflow",
  "prefect",
  "dagster",
  "luigi",
  "dbt",
  "snowflake",
  "databricks",
  "delta lake",
  "iceberg",
  "hudi",
  "apache hive",
  "hive",
  "presto",
  "trino",
  "apache druid",
  "clickhouse",
  "apache storm",
  "apache samza",
  "apache pulsar",
  "pulsar",
  "apache camel",
  "apache nifi",
  "nifi",
  "talend",
  "informatica",
  "pentaho",
  "etl",
  "elt",
  "cdc",
  "change data capture",
];

const CLOUD_INFRA = [
  "docker",
  "containerd",
  "kubernetes",
  "k8s",
  "helm",
  "istio",
  "linkerd",
  "consul",
  "nomad",
  "terraform",
  "pulumi",
  "ansible",
  "chef",
  "puppet",
  "saltstack",
  "jenkins",
  "circleci",
  "github actions",
  "gitlab ci",
  "azure devops",
  "argocd",
  "fluxcd",
  "flux",
  "spinnaker",
  "tekton",
  "prometheus",
  "grafana",
  "datadog",
  "new relic",
  "splunk",
  "elasticsearch",
  "opensearch",
  "loki",
  "tempo",
  "jaeger",
  "zipkin",
  "opentelemetry",
  "otel",
  "aws",
  "amazon web services",
  "ec2",
  "s3",
  "lambda",
  "ecs",
  "eks",
  "fargate",
  "batch",
  "glue",
  "emr",
  "athena",
  "redshift",
  "rds",
  "dynamodb",
  "aurora",
  "sns",
  "sqs",
  "kinesis",
  "step functions",
  "api gateway",
  "cloudfront",
  "route53",
  "vpc",
  "iam",
  "kms",
  "secrets manager",
  "parameter store",
  "cloudwatch",
  "x-ray",
  "azure",
  "azure kubernetes service",
  "aks",
  "azure functions",
  "azure sql",
  "cosmos db",
  "blob storage",
  "azure devops",
  "gcp",
  "google cloud",
  "google kubernetes engine",
  "gke",
  "bigquery",
  "cloud functions",
  "cloud run",
  "pub/sub",
  "firebase",
  "vertex ai",
  "cloudflare",
  "fastly",
  "akamai",
  "nginx",
  "haproxy",
  "envoy",
  "traefik",
  "linux",
  "unix",
  "bsd",
  "ubuntu",
  "debian",
  "red hat",
  "centos",
  "fedora",
  "alpine",
  "windows server",
  "powershell",
];

const DATABASES = [
  "postgresql",
  "postgres",
  "mysql",
  "mariadb",
  "sqlite",
  "oracle",
  "microsoft sql server",
  "sql server",
  "mssql",
  "mongodb",
  "cassandra",
  "cockroachdb",
  "cockroach",
  "neo4j",
  "arangodb",
  "redis",
  "memcached",
  "elasticache",
  "dynamodb",
  "couchbase",
  "rethinkdb",
  "timescaledb",
  "influxdb",
  "prometheus",
  "vitess",
  "planetscale",
  "supabase",
  "neon",
];

const ARCH_PRACTICES = [
  "microservices",
  "monolith",
  "event-driven",
  "cqrs",
  "event sourcing",
  "domain-driven design",
  "ddd",
  "clean architecture",
  "hexagonal architecture",
  "full-stack",
  "fullstack",
  "full stack",
  "end-to-end",
  "e2e",
  "distributed systems",
  "high availability",
  "load balancing",
  "sharding",
  "partitioning",
  "replication",
  "consensus",
  "raft",
  "paxos",
  "cap theorem",
  "acid",
  "eventually consistent",
  "multi-tenant",
  "zero downtime",
  "blue-green deployment",
  "canary deployment",
  "feature flags",
  "ci/cd",
  "continuous integration",
  "continuous deployment",
  "continuous delivery",
  "tdd",
  "bdd",
  "pair programming",
  "agile",
  "scrum",
  "kanban",
  "devops",
  "gitops",
  "platform engineering",
  "sre",
  "site reliability",
  "observability",
  "chaos engineering",
  "performance tuning",
  "profiling",
  "benchmarking",
  "low-latency",
  "low latency",
  "real-time",
  "real time",
  "near real-time",
  "streaming",
  "batch processing",
  "serverless",
  "faas",
  "edge computing",
  "cdn",
];

const SECURITY = [
  "oauth",
  "oauth2",
  "ldap",
  "active directory",
  "okta",
  "auth0",
  "keycloak",
  "vault",
  "hashicorp vault",
  "kms",
  "hsm",
  "penetration testing",
  "static analysis",
  "dynamic analysis",
  "sast",
  "dast",
  "owasp",
  "security engineering",
  "secure coding",
  "threat modeling",
  "siem",
  "soc",
  "zero trust",
];

const MOBILE_EMBEDDED = [
  "ios",
  "android",
  "swift",
  "swiftui",
  "uikit",
  "jetpack compose",
  "kotlin multiplatform",
  "flutter",
  "react native",
  "xamarin",
  "ionic",
  "cordova",
  "capacitor",
  "embedded",
  "firmware",
  "bare metal",
  "rtos",
  "freertos",
  "zephyr",
  "mbed",
  "arduino",
  "raspberry pi",
  "stm32",
  "arm",
  "cortex",
  "riscv",
  "fpga",
  "verilog",
  "vhdl",
  "pcb",
  "hardware-in-the-loop",
  "hil",
  "sil",
  "mil",
  "can bus",
  "ethercat",
  "modbus",
  "ros",
  "ros2",
  "robot operating system",
  "gazebo",
  "rviz",
  "moveit",
  "nvidia isaac",
  "autonomous",
  "autonomy",
  "robotics",
  "perception",
  "localization",
  "motion planning",
  "path planning",
  "manipulation",
  "uav",
  "ugv",
  "drone",
  "lidar",
  "radar",
  "imu",
  "gnss",
  "gps",
  "ins",
  "v2x",
  "adas",
  "drive-by-wire",
];

const GRAPHICS_PERF = [
  "opengl",
  "directx",
  "vulkan",
  "metal",
  "webgl",
  "webgpu",
  "shader",
  "hlsl",
  "glsl",
  "cuda",
  "opencl",
  "rocblas",
  "hip",
  "simd",
  "sse",
  "avx",
  "neon",
  "wasm",
  "webassembly",
];

const MATH_CS = [
  "mathematics",
  "maths",
  "linear algebra",
  "calculus",
  "statistics",
  "probability",
  "bayesian",
  "numerical analysis",
  "optimization",
  "convex optimization",
  "numerical methods",
  "differential equations",
  "discrete mathematics",
  "graph theory",
  "combinatorics",
  "algorithms",
  "data structures",
  "complexity theory",
  "distributed algorithms",
  "parallel computing",
  "multithreading",
  "concurrency",
  "lock-free",
  "atomics",
  "gpu programming",
  "heterogeneous computing",
];

const FINANCE_DOMAIN = [
  "fintech",
  "payments",
  "stripe",
  "adyen",
  "pci-dss",
  "pci",
  "card processing",
  "ach",
  "swift",
  "iban",
  "swift network",
  "ledger",
  "double-entry",
  "reconciliation",
  "risk management",
  "quantitative finance",
  "pricing",
  "trading",
  "market data",
  "order management",
  "oms",
  "ems",
  "fix protocol",
  "fix",
  "kdb+",
  "q language",
];

const SOFT_CONCRETE = [
  "technical leadership",
  "engineering management",
  "people management",
  "mentorship",
  "coaching",
  "stakeholder communication",
  "cross-functional collaboration",
  "cross functional",
  "written communication",
  "public speaking",
  "project management",
  "program management",
  "product sense",
  "customer focus",
  "ownership",
  "problem solving",
  "analytical thinking",
];

const NETWORKING = [
  "tcp/ip",
  "udp",
  "http/2",
  "http/3",
  "http2",
  "http3",
  "quic",
  "tls",
  "ssl",
  "dns",
  "vpn",
  "ipsec",
  "bgp",
  "ospf",
  "sdn",
  "nfv",
  "load balancer",
  "reverse proxy",
  "service mesh",
  "cilium",
  "ebpf",
  "xdp",
  "dpdk",
];

const CLEARANCE_CRED = [
  "ts/sci",
  "ts sci",
  "top secret",
  "secret clearance",
  "security clearance",
  "dod",
  "ic",
  "polygraph",
  "citizenship required",
  "phd",
  "ph.d",
  "masters",
  "ms degree",
  "bs degree",
  "b.s",
  "m.s",
];

const WEB_NET_LEGACY = ["html", "css", "sass", "scss", "less", "php", "wordpress", "drupal"];


const CRYPTO_WEB3 = [
  "smart contracts",
  "smart contract",
  "solidity",
  "blockchain",
  "ethereum",
  "evm",
  "defi",
  "decentralized finance",
  "dex",
  "decentralized exchange",
  "amm",
  "automated market maker",
  "layer 2",
  "layer 1",
  "rollup",
  "optimistic rollup",
  "zk-rollup",
  "zero-knowledge",
  "web3",
  "on-chain",
  "off-chain",
  "liquidity",
  "staking",
  "tokenomics",
  "erc-20",
  "erc-721",
  "nft",
  "wallet",
  "hardhat",
  "foundry",
  "ethers.js",
  "web3.js",
  "viem",
  "wagmi",
  "the graph",
  "subgraph",
  "ipfs",
  "consensus",
  "mempool",
  "gas optimization",
  "mev",
  "cryptography",
  "crypto",
];

const CORE_ENGINEERING = [
  "api",
  "apis",
  "backend",
  "back-end",
  "frontend",
  "front-end",
  "production code",
  "code review",
  "open source",
  "open-source",
  "testing",
  "unit testing",
  "integration testing",
  "test coverage",
  "debugging",
  "competitive programming",
  "data structures",
  "computer science",
  "cs fundamentals",
  "ctf",
  "capture the flag",
  "technical writing",
  "pair programming",
  "infrastructure",
  "web development",
  "distributed systems",
  "scalability",
  "production",
  "hackathon",
  "side projects",
  "system design",
  "performance optimization",
];

const ALL = [
  ...LANGUAGES,
  ...CRYPTO_WEB3,
  ...CORE_ENGINEERING,
  ...WEB_PLATFORM,
  ...BACKEND_APIS,
  ...DATA_ML,
  ...DATA_ENG,
  ...CLOUD_INFRA,
  ...DATABASES,
  ...ARCH_PRACTICES,
  ...SECURITY,
  ...MOBILE_EMBEDDED,
  ...GRAPHICS_PERF,
  ...MATH_CS,
  ...FINANCE_DOMAIN,
  ...SOFT_CONCRETE,
  ...NETWORKING,
  ...CLEARANCE_CRED,
  ...WEB_NET_LEGACY,
];

function dedupeNormalized(terms: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const t of terms) {
    const k = t.trim().toLowerCase().replace(/\s+/g, " ");
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(t.trim());
  }
  return out;
}

/** Longer phrases first — used for deterministic matching order. */
export const JD_KEYWORD_ALLOWLIST: readonly string[] = dedupeNormalized(ALL).sort(
  (a, b) => b.length - a.length
);

/**
 * Generic / soft terms. They stay matchable — a JD that stresses ownership or
 * mentorship is telling you something — but they rank below concrete technical
 * terms so they never crowd the top of the list.
 */
export const JD_KEYWORD_SOFT_TERMS: ReadonlySet<string> = new Set(
  SOFT_CONCRETE.map((t) => t.toLowerCase()),
);

/**
 * Short entries that are only meaningful as acronyms. Matched case-sensitively
 * so prose like "we go fast" or "an R&D team" cannot produce a false hit for
 * the Go language or the R language.
 */
export const JD_KEYWORD_CASE_SENSITIVE: ReadonlySet<string> = new Set(
  JD_KEYWORD_ALLOWLIST.filter((t) => t.length <= 3 && !/[+#.]/.test(t)).map((t) =>
    t.toLowerCase(),
  ),
);
